modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="{mod_update_json}"
    displayURL="${mod_homepage}"
    logoFile="${mod_icon}"
    #credits="{mod_credits}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[mixins]]
    config="META-INF/${mod_id}.mixins.json"

#[[accessTransformers]]
    #file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
